#pragma once

#include "pokemon_common.h"

/* Type matchup table adapted from PMD EoS's version: https://github.com/pret/pmd-sky/blob/main/src/type_matchup_table.c
 * Modified to include fairy type (introduced 2013) and use matchup table from gen VI onwards
 * Also re-ordered to match enum Type
 */

#define IMMUNE EFFECTIVENESS_IMMUNE
#define RESIST EFFECTIVENESS_MILDLY_EFFECTIVE
#define NEUTRAL EFFECTIVENESS_NEUTRAL
#define SUPER EFFECTIVENESS_SUPER_EFFECTIVE

const Effectiveness matchups[TYPE_COUNT][TYPE_COUNT] {

    //                TOP ROW (Defending type)
    //                NORMAL    FIGHTING  FLYING   POISON   GROUND   ROCK     BUG      GHOST    STEEL    FIRE     WATER    GRASS    ELECTRIC PSYCHIC  ICE      DRAGON   DARK     FAIRY
    [TYPE_NORMAL]   = {NEUTRAL, NEUTRAL,  NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, IMMUNE,  RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL},
    [TYPE_FIGHTING] = {SUPER,   NEUTRAL,  NEUTRAL, RESIST,  NEUTRAL, SUPER,   RESIST,  NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  SUPER,   NEUTRAL, SUPER,   RESIST},
    [TYPE_FLYING]   = {NEUTRAL, SUPER,    NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  SUPER,   NEUTRAL, RESIST,  NEUTRAL, NEUTRAL, SUPER,   RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL},
    [TYPE_POISON]   = {NEUTRAL, NEUTRAL,  NEUTRAL, RESIST,  RESIST,  RESIST,  NEUTRAL, RESIST,  IMMUNE,  NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER},
    [TYPE_GROUND]   = {NEUTRAL, NEUTRAL,  IMMUNE,  SUPER,   NEUTRAL, SUPER,   RESIST,  NEUTRAL, SUPER,   SUPER,   NEUTRAL, RESIST,  SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL},
    [TYPE_ROCK]     = {NEUTRAL, RESIST,   SUPER,   NEUTRAL, RESIST,  NEUTRAL, SUPER,   NEUTRAL, RESIST,  SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, NEUTRAL},
    [TYPE_BUG]      = {NEUTRAL, RESIST,   RESIST,  RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  RESIST,  RESIST,  NEUTRAL, SUPER,   NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, SUPER,   RESIST},
    [TYPE_GHOST]    = {IMMUNE,  NEUTRAL,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, RESIST,  NEUTRAL},
    [TYPE_STEEL]    = {NEUTRAL, NEUTRAL,  NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, RESIST,  RESIST,  RESIST,  NEUTRAL, RESIST,  NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, SUPER},
    [TYPE_FIRE]     = {NEUTRAL, NEUTRAL,  NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  SUPER,   NEUTRAL, SUPER,   RESIST,  RESIST,  SUPER,   NEUTRAL, NEUTRAL, SUPER,   RESIST,  NEUTRAL, NEUTRAL},
    [TYPE_WATER]    = {NEUTRAL, NEUTRAL,  NEUTRAL, NEUTRAL, SUPER,   SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   RESIST,  RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL},
    [TYPE_GRASS]    = {NEUTRAL, NEUTRAL,  RESIST,  RESIST,  SUPER,   SUPER,   RESIST,  NEUTRAL, RESIST,  RESIST,  SUPER,   RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL},
    [TYPE_ELECTRIC] = {NEUTRAL, NEUTRAL,  SUPER,   NEUTRAL, IMMUNE,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   RESIST,  RESIST,  NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL},
    [TYPE_PSYCHIC]  = {NEUTRAL, SUPER,    NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL, IMMUNE,  NEUTRAL},
    [TYPE_ICE]      = {NEUTRAL, NEUTRAL,  SUPER,   NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  RESIST,  RESIST,  SUPER,   NEUTRAL, NEUTRAL, RESIST,  SUPER,   NEUTRAL, NEUTRAL},
    [TYPE_DRAGON]   = {NEUTRAL, NEUTRAL,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, IMMUNE},
    [TYPE_DARK]     = {NEUTRAL, RESIST,   NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   NEUTRAL, NEUTRAL, RESIST,  RESIST},
    [TYPE_FAIRY]    = {NEUTRAL, SUPER,    NEUTRAL, RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, RESIST,  RESIST,  NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, NEUTRAL, SUPER,   SUPER,   NEUTRAL}
};
